version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.web
      args:
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - backend

  ws:
    build:
      context: .
      dockerfile: ./Dockerfile.ws
    ports:
      - "8081:8081"
    depends_on:
      - backend

  db:
    image: postgres:15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MYDB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
